services:
  - type: web
    name: learning-log-pwa
    env: python
    buildCommand: pip install -r requirements.txt
    releaseCommand: alembic upgrade head
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT