"""create logs table

Revision ID: ebf99da6f82c
Revises: 2b3c537933c2
Create Date: 2025-06-24 22:33:16.467255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf99da6f82c'
down_revision: Union[str, Sequence[str], None] = '2b3c537933c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('calendar_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'calendar_id')
    # ### end Alembic commands ###
